# Tensor

In [2]:
import torch 
import numpy as np
import time
import random

In [2]:
# https://pytorch.org/
torch.__version__ # 查看pytorch版本

'1.13.0+cu117'

## 张量创建

In [6]:
# torch.Tensor是torch.Tensor类的构造函数，使用全局默认dtype(FloatTensor)
a = torch.Tensor(2,2)
b = torch.Tensor([[1,2],[3,4]])
print(a)
print(b)
print(a.type())
print(a.dtype)
print(b.type())
print(b.dtype)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor
torch.float32
torch.FloatTensor
torch.float32


In [5]:
# torch.tensor()是一个普通函数
a = torch.tensor([[1,2],[3,4]])
print(a)
print(a.type())
print(a.dtype)

tensor([[1, 2],
        [3, 4]])
torch.LongTensor
torch.int64


In [5]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.eye(3,3) #对角为1，其余为0

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [8]:
torch.arange(0,1,0.1) #间隔步长

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])

In [9]:
torch.linspace(0,1,3) #等分

tensor([0.0000, 0.5000, 1.0000])

In [10]:
# (0,1)均匀分布
#torch.manual_seed(10)
torch.rand(3,3)

tensor([[0.1664, 0.3571, 0.7323],
        [0.3812, 0.2148, 0.3365],
        [0.6886, 0.8005, 0.2762]])

In [11]:
torch.randn(3,3)

tensor([[ 0.3451,  0.9314, -0.9760],
        [-0.0545,  0.6617,  0.8082],
        [ 0.7776,  0.7376,  1.0511]])

In [12]:
torch.randperm(10)

tensor([9, 8, 5, 7, 1, 6, 3, 4, 0, 2])

## 数据类型 

In [13]:
# 查看默认数据类型
torch.get_default_dtype() 

torch.float32

In [14]:
# 创建一个Tenseor,不另外指定数据类型
a = torch.Tensor([[1,2],[3,4]])
# 指定数据类型为64位浮点型数据
#a = torch.DoubleTensor([[1,2],[3,4]])
print(a)
# 查看数据类型
print(a.dtype)

tensor([[1., 2.],
        [3., 4.]])
torch.float32


In [15]:
# 更改默认的数据类型
#torch.set_default_tensor_type(torch.DoubleTensor) 
torch.set_default_dtype(torch.float64)
torch.get_default_dtype() 

torch.float64

In [16]:
a = torch.Tensor([[1,2],[3,4]])
print(a) 
print(a.dtype)

tensor([[1., 2.],
        [3., 4.]])
torch.float64


In [17]:
print(a.device)

cpu


In [18]:
torch.cuda.is_available()

True

In [19]:
a = a.cuda()
print(a.device)

cuda:0


In [20]:
a = a.cpu() 
print(a.device)

cpu


In [21]:
a=torch.cuda.FloatTensor([[1,2],[3,4]])  
print(a) 
print(a.dtype) 
print(a.device)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0', dtype=torch.float32)
torch.float32
cuda:0


In [7]:
a=torch.ByteTensor([[1,2],[3,4]])  
print(a) 
print(a.dtype) 
print(a.device)

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)
torch.uint8
cpu


In [8]:
a=torch.BoolTensor([[1,2],[3,4]])  
print(a) 
print(a.dtype) 

tensor([[True, True],
        [True, True]])
torch.bool


In [14]:
a=torch.empty(1,2)
print(a)
print(a.dtype)
print(a.type())
torch.set_default_dtype(torch.float64)
a=torch.empty(1,2)
print(a)
print(a.dtype)
print(a.type())

tensor([[9.1477e-41, 1.8750e+00]])
torch.float32
torch.FloatTensor
tensor([[4.9407e-324, 4.9407e-324]])
torch.float64
torch.DoubleTensor


## Tensor的属性

In [22]:
a = torch.Tensor([[1,2],[3,4],[5,6]])
# 可以通过下面两种方式得到 tensor 的大小
print(a.shape) # shape是 tensor 的属性
print(a.size()) # size() 是tensor 的方法
# 得到tensor数组元素的数据类型
print(a.dtype)
# 得到 tensor 的数据结构类型 
print(a.type())
# 得到 tensor 的维度 
print(a.dim())
# 得到 tensor 的所有元素个数 
print(a.numel())

torch.Size([3, 2])
torch.Size([3, 2])
torch.float64
torch.DoubleTensor
2
6


## Tensor的操作

In [23]:
x = torch.ones(2, 2) # 生成全1的2*2张量
print(x)
print(x.dtype) # tensor 数据元素的数据类型
print(x.type()) # tensor 数据结构类型
print('##############################')
x = x.long()
print(x) 
print(x.dtype) 
print(x.type())
print('##############################')
x = x.float() 
print(x)  
print(x.dtype)  
print(x.type())
print('##############################')
x = torch.randn(4, 3) 
print(x)
print('##############################')
max_value, max_idx = torch.max(x, dim=1) # 沿着行取最大值，“dim=0”表示按列
print(max_value) # 每一行的最大值
print(max_idx) # 每一行最大值的下标
print('##############################')
# 沿着行对 x 求和 
sum_x = torch.sum(x, dim=1) 
print(sum_x)

tensor([[1., 1.],
        [1., 1.]])
torch.float64
torch.DoubleTensor
##############################
tensor([[1, 1],
        [1, 1]])
torch.int64
torch.LongTensor
##############################
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float32)
torch.float32
torch.FloatTensor
##############################
tensor([[-1.7313,  1.5546, -0.7664],
        [ 0.4415, -0.1830, -1.8320],
        [ 1.3183,  1.8307,  0.7216],
        [-1.1192,  0.1467,  0.5428]])
##############################
tensor([1.5546, 0.4415, 1.8307, 0.5428])
tensor([1, 0, 1, 2])
##############################
tensor([-0.9432, -1.5735,  3.8705, -0.4298])


## 张量的索引

In [24]:
# 一维张量索引
t1 = torch.arange(1, 11)
print(t1)
print(t1[0])
print(t1[:8:2]) # 从第一个元素开始索引到第9个元素（不包含），并且每隔两个数取一个

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor(1)
tensor([1, 3, 5, 7])


In [25]:
# 二维张量索引
t2 = torch.arange(1, 10).reshape(3, 3)
print(t2)
print(t2[0,::2])                # 表示索引第一行、每隔两个元素取一个,注：“:“左右两边为空代表全取

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 3])


## 张量的合并操作

In [26]:
a = torch.zeros(2, 3)
b = torch.ones(2, 3)
c = torch.cat([a, b]) 
print(a)
print('##############################')
print(b)
print('##############################')
print(c)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 与Numpy配合使用

In [27]:
# 创建一个 numpy ndarray 
# np.random.seed(0) 
numpy_ndarray1 = np.random.randn(2, 2)
print(numpy_ndarray1)
print(numpy_ndarray1.dtype)

[[ 0.1948142  -1.10972952]
 [-2.53956816 -0.97349902]]
float64


In [28]:
# 使用下面两种方式将numpy的ndarray转换到tensor上
pytorch_tensor1 = torch.tensor(numpy_ndarray1) 
pytorch_tensor2 = torch.from_numpy(numpy_ndarray1)
print(pytorch_tensor1)
print(pytorch_tensor1.dtype)
print(pytorch_tensor2)
print(pytorch_tensor2.dtype)

tensor([[ 0.1948, -1.1097],
        [-2.5396, -0.9735]])
torch.float64
tensor([[ 0.1948, -1.1097],
        [-2.5396, -0.9735]])
torch.float64


In [3]:
a=np.array([1,2,3])
a=torch.from_numpy(a)
print(a.type())
print(a.dtype)

torch.IntTensor
torch.int32


In [4]:
a=np.array([2,3.3])
a=torch.from_numpy(a)
print(a.type()) # torch.DoubleTensor
print(a.dtype) #

torch.DoubleTensor
torch.float64


In [29]:
# 使用下面的方法将 pytorch tensor 转换为 numpy ndarray
numpy_ndarray2 = pytorch_tensor1.numpy()
print(numpy_ndarray2)
print(numpy_ndarray2.dtype)

[[ 0.1948142  -1.10972952]
 [-2.53956816 -0.97349902]]
float64


In [30]:
# 需要注意 GPU 上的 Tensor 不能直接转换为 NumPy ndarray
x = torch.rand(3,3)
#x = x.cuda()
#x.numpy()
x = x.cpu()
x.cpu().numpy()

array([[0.98371312, 0.01343232, 0.18982422],
       [0.22842761, 0.33301664, 0.26185812],
       [0.68386788, 0.63938776, 0.31998353]])

## Pytorch与Numpy运行时间对比

In [31]:
na = np.random.rand(1000,1000)
nb = np.random.rand(1000,1000)

na_tensor_cpu = torch.Tensor(na)  
nb_tensor_cpu = torch.Tensor(nb)

na_tensor_gpu = na_tensor_cpu.cuda() 
nb_tensor_gpu = nb_tensor_cpu.cuda() 

In [32]:
# %timeit -r R -n N，以自定义的设置（运行R次，每一次N遍）来运行代码并计时
%timeit -r 5 -n 1000 na+nb
%timeit -r 5 -n 1000 na-nb
%timeit -r 5 -n 1000 na*nb
%timeit -r 5 -n 1000 na/nb

1.95 ms ± 61.6 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.98 ms ± 77.4 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.94 ms ± 52.7 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.99 ms ± 20.5 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)


In [33]:
%timeit  -r 5 -n 1000 na_tensor_cpu+nb_tensor_cpu
%timeit  -r 5 -n 1000 na_tensor_cpu-nb_tensor_cpu
%timeit  -r 5 -n 1000 na_tensor_cpu*nb_tensor_cpu
%timeit  -r 5 -n 1000 na_tensor_cpu/nb_tensor_cpu

1.18 ms ± 110 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.1 ms ± 5.22 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.12 ms ± 23.2 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
1.12 ms ± 26 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)


In [34]:
%timeit  -r 5 -n 1000 na_tensor_gpu+nb_tensor_gpu
%timeit  -r 5 -n 1000 na_tensor_gpu-nb_tensor_gpu
%timeit  -r 5 -n 1000 na_tensor_gpu*nb_tensor_gpu
%timeit  -r 5 -n 1000 na_tensor_gpu/nb_tensor_gpu

The slowest run took 25.83 times longer than the fastest. This could mean that an intermediate result is being cached.
158 µs ± 117 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
132 µs ± 5.48 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
135 µs ± 670 ns per loop (mean ± std. dev. of 5 runs, 1,000 loops each)
132 µs ± 10.4 µs per loop (mean ± std. dev. of 5 runs, 1,000 loops each)


## Tensor维度变换

### 1、改变Shape

In [35]:
a = torch.randn(4, 1, 28, 28)
print(a.shape)
print(a.view(4 * 1, 28, 28).shape)
print(a.reshape(4 * 1, 28, 28).shape)
print(a.reshape(4, 1 * 28 * 28).shape)

torch.Size([4, 1, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 28, 28])
torch.Size([4, 784])


### 2、增加维度

这个Tensor有4个维度，我们可以在现有维度的基础上插入一个新的维度，插入维度的index在[-a.dim()-1, a.dim()+1)范围内，并且当index>=0，则在index前面插入这个新增加的维度；当index < 0，则在index后面插入这个新增的维度。

In [36]:
a = torch.randn(4, 1, 28, 28)
print(a.shape)
print(a.unsqueeze(0).shape)
print(a.unsqueeze(-1).shape)
print(a.unsqueeze(3).shape)
print(a.unsqueeze(4).shape)
print(a.unsqueeze(-4).shape)
print(a.unsqueeze(-5).shape)
#print(a.unsqueeze(5).shape)

torch.Size([4, 1, 28, 28])
torch.Size([1, 4, 1, 28, 28])
torch.Size([4, 1, 28, 28, 1])
torch.Size([4, 1, 28, 1, 28])
torch.Size([4, 1, 28, 28, 1])
torch.Size([4, 1, 1, 28, 28])
torch.Size([1, 4, 1, 28, 28])


### 3、删减维度

In [37]:
a = torch.Tensor(1, 4, 1, 9)
print(a.shape)
print(a.squeeze().shape) # 删除所有的size=1的维度
print(a.squeeze(0).shape) # 删除0号维度,ok
print(a.squeeze(2).shape) # 删除2号维度,ok
print(a.squeeze(3).shape) # 删除3号维度,但是3号维度是9不是1,删除失败

torch.Size([1, 4, 1, 9])
torch.Size([4, 9])
torch.Size([4, 1, 9])
torch.Size([1, 4, 9])
torch.Size([1, 4, 1, 9])
